name: mangadex_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  collection: ^1.19.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.9.0
  mangadexapi_flutter:
    path: ../mangadexapi_flutter
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  drift_dev: ^2.21.2

flutter:
  uses-material-design: true
